# Copyright (c) 2022 Sapphire's Suite. All Rights Reserved.

name: Benchmark

# Trigger the action.
on:
  push:
    branches:
      - benchmark
      - bench_*


# Settings common to all jobs.
defaults:
  run:
    shell: bash


# Variables common to all jobs.
env:
  CMAKE_V: '3.17.0'
  CMAKE_OPTIONS: '-DSA_CI=1 -DSA_MATHS_BUILD_TESTS_OPT=ON -DSA_MATHS_BUILD_BENCHMARK_OPT=ON'


# Job matrix
jobs:

  ctests_unix:
    name: ${{ matrix.compiler }} ${{ matrix.compiler_v }} (SIMD:${{ matrix.option_SIMD }})

    # Setup environment.
    runs-on: ubuntu-latest

    strategy:

      # Don't cancel jobs on failure.
      fail-fast: false

      matrix:

        config:
          - Release

        compiler:
          - GNU
          - Clang

        compiler_v: [9, 10, 11]

        gen:
          - Ninja

        option_SIMD: [ON, OFF]


    # Steps execution.
    steps:

        - name: "[Action] Checkout repository"
          uses: actions/checkout@v2
          with:
            submodules: recursive


         # Install GCC.
        - name: "[Package] Install GCC"
          if: ${{ matrix.compiler == 'GNU' }}
          run: |
              sudo apt-get install g++-${{ matrix.compiler_v }}
              echo "CC=gcc-${{ matrix.compiler_v }}" >> $GITHUB_ENV
              echo "CXX=g++-${{ matrix.compiler_v }}" >> $GITHUB_ENV


        # Install Clang.
        - name: "[Package] Install LLVM and Clang"
          if: ${{ matrix.compiler == 'Clang' }}
          run: |
              sudo apt-get install clang-${{ matrix.compiler_v }}
              echo "CC=clang-${{ matrix.compiler_v }}" >> $GITHUB_ENV
              echo "CXX=clang++-${{ matrix.compiler_v }}" >> $GITHUB_ENV


        # Install CMake.
        - name: "[Action] Install CMake"
          uses: jwlawson/actions-setup-cmake@v1.8
          with:
            cmake-version: ${{ env.CMAKE_V }}


        # Install Ninja.
        - name: "[Action] Install Ninja 1/2"
          if: ${{ matrix.gen == 'Ninja' }}
          uses: seanmiddleditch/gha-setup-ninja@master

        # Set env variables.
        - name: "[Command] Install Ninja 2/2"
          if: ${{ matrix.gen == 'Ninja' }}
          run: echo "GEN=Ninja" >> $GITHUB_ENV


        # Deploy & Build & Test
        - name: Generate Project
          run: cmake -B Build/${{ matrix.gen }}/${{ matrix.config }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DSA_MATHS_INTRINSICS_OPT=${{ matrix.option_SIMD }} ${{ env.CMAKE_OPTIONS }} -G "${GEN}"

        - name: Build Project
          run: cmake --build Build/${{ matrix.gen }}/${{ matrix.config }} --target SA_MathsBenchmark --config ${{ matrix.config }} --verbose

        - name: Run Benchmark
          run: cd Build/${{ matrix.gen }}/${{ matrix.config }}/Bin && ./SA_MathsBenchmark
